"""
Django settings for ZYBShop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '612c^ovp45-wy1eqcjzn!v3@kxlw-u)0gn_@+n2j1r6z28y(7('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ZYBShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,    #是否加载app下的templates文件
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ZYBShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIR=(
    os.path.join(BASE_DIR,"static"),
)


# STATIC_ROOT=os.path.join(BASE_DIR,'static')   #静态文件的根目录，与STATICFILES_DIRS,MEDIA_URL,MEDIA_ROOT有冲突


MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'static')



DING_URL="https://oapi.dingtalk.com/robot/send?access_token=cb82eac0becb2ab4bd2729da84e733944e7824e91993844a5cd74223530fe04c"

#支付宝支付功能所需配置环境
alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAod5RzLQRM/rggsMUWaCHPS9v25pfq5SOZnckO8CgWou4i3A49IjXWJFma6xBVXc8/5Tt6kcTZp0hx2EPBDWJ8Fwjd1+B3K48T/UwzuOhIfe0M/8MoOoTaGd2F28ShH80RPNVJxXGaujZdJ4tBR7ZW3a8AUHHQAZtAEwCZdrcDyTRcQZ5DDxmQmha0VVoyVz/tBXZoGqGzqu724a9BMyhOYcC1TB61VOGFgdOcFsxdzJRSwizw+wUCq66D9Gj3ybpiR4VS2iZL7TuxT8c92a6oSFuPhlQNC/p6iaf1XMtp5JhGulEYIMqjroOmRSIt7VlaFrtvl/d0MHikmrxEKB34QIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAod5RzLQRM/rggsMUWaCHPS9v25pfq5SOZnckO8CgWou4i3A49IjXWJFma6xBVXc8/5Tt6kcTZp0hx2EPBDWJ8Fwjd1+B3K48T/UwzuOhIfe0M/8MoOoTaGd2F28ShH80RPNVJxXGaujZdJ4tBR7ZW3a8AUHHQAZtAEwCZdrcDyTRcQZ5DDxmQmha0VVoyVz/tBXZoGqGzqu724a9BMyhOYcC1TB61VOGFgdOcFsxdzJRSwizw+wUCq66D9Gj3ybpiR4VS2iZL7TuxT8c92a6oSFuPhlQNC/p6iaf1XMtp5JhGulEYIMqjroOmRSIt7VlaFrtvl/d0MHikmrxEKB34QIDAQABAoIBAQCT+5dXCQxtNB/LDCPvqKXbFyIxZ1mtmHvzS1rx0bIH9ZK6z9cSIISXsR4ss+drBj7a/kHgHCiteFwoViCPXY8FEodOHB+yLAxxoRyFGG/4iOfTXYojFry1h1jcJayNO2oC219vAyZKGSSsy+smskROrSdGEufhLb67NcI/ci4bHL6yPAfrr8IikqL/KCkkxX+Gr9ywTaGrc5y8b4VorYlNOVkWdkXphIQbpD0tVKvT2q/WsYj75CvoJW8enHbTsngDWU7Eo53F7CqZ9j/71ZLs+n9QqD4rM3ogn1pQFIHF4/h+ugKrGR66ixjvRbm7OzHxtd6jn5kR0RKrrTU157aRAoGBAMzXljnp8RCBcVLxAR3p4V2ckxq6mdqLdzWtlYJeZPyYrFhYknPZJxSvzw+TRLasW56zApn8DBpFyZwL4Cb7mExnIF3KHQvUMs55qWJECf8cceYRi7DhMMn85FApTQsQAe1+gaAnBSq/IhP/F3hXXgeSfkwf6X37m3gIPaEN3J6lAoGBAMpLPp0x37135e3M/poPQOP7DGk+/nSIeBIddzE9mpQIu+jbQsGRK4jTcRcxeYQvkNpQ0T6IanJi+tn3xsEnSF8cWp9RQnMT8vU4rtlORp4wIHIieuMhX+4pePAvEfSomt8BzqEjo1xUXWo7uJFnc46koMpXFeosR1xse2wwXAuNAoGBAJBz17SvjRgesFPVMPxvWkYxjGtk++pqP37TEoQFHSIkaCVFEMIxeKXV9Sb+q45GrbWUd1kvrTk5zZsFpOTYt+XpM6HwTdtxoQKKOTDa2lHVNV0RMnlh1I4ckMUW2wXaHAHnHHJcEgC7GMURNvPeaKjeXcJBHt+A93oGFa/lnpchAoGAWkiEtGFq6sOVEbGYu6ctHdKQcnRT2iyB8gvGg2psD79qJf2daIhitpkvctt40T7tVhIVoOP/Jff43sjPoqrmiNQ9ubbpgjSYDUtz9bYSnEz8XhP3ZmEh0EggGonXaKrLG9ZRoucl5HIekuf+cp6KG1JsFIITXMTQQHaGCv32Ro0CgYEAsRhBrybj0K7KQhvNcRs165g61IkztwG7NmViskV88MFsvb1dfu6sVRd5AZA967dPQWYF52pRgiGe4s+UC2GoCd27dx8prHDf0J6LUhni1ZkFL5Ctda5AG+wfMpvIAacIM5CiV8Mc8N1mFGwL+hRrLN3PoOacYV+OIMdPewuYVjM=
-----END RSA PRIVATE KEY-----"""